version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kuberlr
    ldflags:
      - -X=github.com/flavio/kuberlr/pkg/kuberlr.Version={{.Version}}
      - -X=github.com/flavio/kuberlr/pkg/kuberlr.BuildDate={{.Date}}
      - -X=github.com/flavio/kuberlr/pkg/kuberlr.Tag={{.Tag}}
    goos:
      - linux
    goarch:
      - amd64
release:
universal_binaries:
  - replace: false
archives:
  - wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  # Delegate Changelog to release-drafter
  disable: true
